# Generated by Django 4.1.2 on 2022-11-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
